### PR TITLE
Refactor: Do config loading (bootstrap) at runtime rather module load time

### PR DESCRIPTION
**Pull request by glensc**
Fixes https://github.com/moogar0880/PyTrakt/issues/150

### CODE REVIEW

**Comment by glensc** [comment]
The `@_boostrapped` needs access to some `s` variable, which seems to be extracted from caller and is really instance of `Core()`, but since Core() is already globally instantiated, can just reference that instead.

And in fact, the "s" is just used to access logger, so forget all that and export logger as "trakt" module global?

**Comment by glensc** [comment]
or just move the _validate_token, _refresh_token, etc method to Core class...

**Comment by glensc** [comment]
@moogar0880 simplified, just call the bootstrap method prior to actual get/post/put methods.

**Comment by glensc** [comment]
@twolaw do you want to test this and give your opinion?

**Comment by moogar0880** [comment]
@glensc this change seems reasonable. did you get a chance to test this out and verify that it indeed resolves the lazy init issue?

**Comment by glensc** [comment]
@moogar0880 yes, I've tested this. I re-did the branch 4 times here, this is the final the most simplest solution :)

**Review by moogar0880 — APPROVED** [review]

**Comment by glensc** [comment]
This is great. exactly as I wanted, release this as 3.4.0 and the other new methods can wait for review and improvements. :)

**Pull request merged**
