### PR TITLE
Fix list retrieval

### PR DESCRIPTION
**Pull request by permster**
Fix for issue #37.

### CODE REVIEW

**Comment by moogar0880** [comment]
Looks like there's some syntax errors in there, my guess is probably from copy+pasting a diff. You mind take another crack at fixing that up?

**Comment by permster** [comment]
Should be looking a little better now.  Sorry about that.

**Comment by moogar0880** [comment]
No problem. Still a couple issues though. Looks like there are some duplicate fields and another syntax error (looks like you're closing your parenthesis/brackets in two places

```python
In [1]: import trakt.users
  File "/Users/Jon/Programs/Github/PyTrakt/trakt/users.py", line 62
    'likes', 'trakt', 'slug', 'user', 'creator'])):
                                               ^
SyntaxError: invalid syntax
```

**Comment by permster** [comment]
Think I finally have it.  Sorry I'm not at home right now so I editing directly off the github webpage.  I'll double check from home later but I think that should do it.

**Comment by permster** [comment]
Yeah my latest commit looks good to me.  Just tested using self.user.lists and no more unexpected keyword errors.

**Comment by moogar0880** [comment]
Looks good! Thanks!

**Pull request merged**
