### PR TITLE
Add global session object for requests

### PR DESCRIPTION
**Pull request by glensc**
The intent is to be able to override in client libraries with requests_cache for example:
- https://github.com/reclosedev/requests-cache/issues/289

----

```py
        trakt.core.session = CachedSession()
        trakt.init(client_id=client_id, client_secret=client_secret, store=True)

```

### CODE REVIEW

**Comment by glensc** [comment]
@moogar0880 what you think of this?

should add a method to override session, or overwriting module globals is ok like rest of the stuff being overwritten?

**Comment by moogar0880** [comment]
> should add a method to override session, or overwriting module globals is ok like rest of the stuff being overwritten?

You can add some get/set functions if you'd like but I think this seems fine as-is given that the rest of the globals are all expected to be accessed directly.

**Comment by glensc** [comment]
@moogar0880 great. let's have it as is then.

do you think this is backward compatible change?

**Comment by moogar0880** [comment]
@glensc yeah this should be fine WRT backwards compatibility since this wasn't something users had the ability to control in previous versions. So once this PR lands I'll get a 3.2.0 release out for this change

**Comment by glensc** [comment]
@moogar0880 thanks for the release!

**Pull request merged**
