### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by StoneMonarch**
Fix the same season number showing in `TVShow.seasons` for each season
screenshot from 2019-02-18 19-48-36

### CODE REVIEW

**Comment by iantrich** [comment]
@StoneMonarch thanks for finding my error

**Comment by StoneMonarch** [comment]
@moogar0880 Fix your runners, this code will pass without errors if your runners actualy get to the tests

**Comment by moogar0880** [comment]
@StoneMonarch yeah, looks like some of the travis bits got out of whack there. Just merged a fix to master though, so if you rebase your PR onto master then this should be good

**Comment by iantrich** [comment]
pumped for this fix 😄 thanks, guys!

**Pull request closed without merging**
